### ISSUE TITLE
error running collectDataYoutube()

### ISSUE THREAD

**Issue by LubinLemarchand** [voson-lab/SocialMediaLab#12] opened 2016-04-28 08:26 UTC
Hi,
 i tried to run the collectYoutubeData() function and i'm running into this error message : 
```
> myYoutubeData <- CollectDataYoutube( c("W2GZFeYGU3s","mL27TAJGlWc"),
+                                      apiKeyYoutube,writeToFile=TRUE,verbose = TRUE)

Now scraping video number: 1 (out of 2 videos in total).....
Now scraping video number: 2 (out of 2 videos in total).....
Now cleaning and structuring data... please be patient...
Error in split.default(matchTemp, ceiling(seq_along(matchTemp)/length(commentsTextCleaned))) : 
  first argument must be a vector
```

Does anyone knows what i've done wrong?

**Comment by timothyjgraham** [comment] 2016-04-28 13:24
Thanks for posting this - I will look into it ASAP.

**Comment by timothyjgraham** [comment] 2016-04-30 04:13
Hi @LubinLemarchand, it appears you are using the deprecated function `collectYoutubeData()`. This may be the cause of the problems. I am going to remove this and other deprecated functions in a future release.

I have used the following code and it works. Could you please let me know if it works for you? Note: it uses the Magrittr pipe interface, so it passes the data through the "pipeline". You can separate out the steps if you like (I can send you example code).

```
apiKey <- "YOUR-KEY-HERE"
videoIDs <- c("W2GZFeYGU3s","mL27TAJGlWc")

myGraph_youtube <- Authenticate("youtube", apiKey= apiKey) %>% 
Collect(videoIDs = videoIDs,writeToFile=TRUE,verbose=TRUE) %>% 
Create("Actor")
```

**Comment by LubinLemarchand** [comment] 2016-04-30 08:58
Hi @timothyjgraham,

i removed the package and reinstalled it (v 0.22.0). I still have the same error message with both codes.

**Comment by timothyjgraham** [comment] 2016-04-30 12:11
Hi, @LubinLemarchand, the latest version should be 0.22.3. Are you installing from GitHub? I have not updated the CRAN version yet. You can install from GitHub via:

`devtools::install_github("voson-lab/SocialMediaLab/SocialMediaLab")`

**Comment by LubinLemarchand** [comment] 2016-04-30 17:04
Makes sens. Works like a charm thank you very much.

**Comment by timothyjgraham** [comment] 2016-04-30 21:46
Great! Glad it's working. Thanks for posting this bug. I will close the issue now.

**Closed by timothyjgraham** 2016-04-30 21:46 UTC
